# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RACSignal' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
 pod 'ReactiveObjC'
  # Pods for RACSignal

  target 'RACSignalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RACSignalUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
