# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RAC映射' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
 pod 'ReactiveObjC'
  # Pods for RAC映射

  target 'RAC映射Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RAC映射UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
