# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RAC过滤' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'ReactiveObjC'
  # Pods for RAC过滤

  target 'RAC过滤Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RAC过滤UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
