# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RAC绑定' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
 pod 'ReactiveObjC'
  # Pods for RAC绑定

  target 'RAC绑定Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RAC绑定UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
