# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RAC组合' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'ReactiveObjC'
  # Pods for RAC组合

  target 'RAC组合Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RAC组合UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
